language: java

matrix:
  include:
    # License, formatter, and FindBugs check
    - env: NAME="License, formatter, and FindBugs check"
      os: linux
      sudo: false
      jdk: openjdk8
      script:
        - mvn license:check
        - mvn formatter:validate
        - mvn findbugs:check

    # Coverage report
    - env: NAME="Coverage report"
      os: linux
      sudo: false
      jdk: openjdk8
      script:
        - mvn cobertura:cobertura
      after_success:
        - mvn coveralls:report

    # Linux tests (Java 8 LTS)
    - env: NAME="Linux tests (Java 8)"
      os: linux
      sudo: false
      jdk: openjdk8
      script:
        - mvn test

    # Linux tests (Java 11 LTS)
    - env: NAME="Linux tests (Java 11)"
      os: linux
      sudo: false
      jdk: openjdk11
      script:
        - mvn test

    # macOS tests (Java 8 LTS)
    - env: NAME="macOS tests"
      os: osx
      osx_image: xcode9.2
      script:
        - mvn test

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/Library/Caches/Homebrew

before_install:
  - rm ~/.m2/settings.xml || true # remove the default settings.xml in order to use custom repos
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source .travis/linux_start_xvfb.sh; fi
