language: java
matrix:
  include:
    # Linux license, format, and coverage check
    - os: linux
      sudo: false
      jdk: openjdk8
      script:
        - mvn license:check
        - mvn formatter:validate
        - mvn cobertura:cobertura
      after_success:
        - mvn coveralls:report

    # Linux tests
    - os: linux
      sudo: false
      jdk: oraclejdk8
      script:
        - mvn test

    # macOS tests
    - os: osx
      osx_image: xcode9.2
      script:
        - mvn test

    # Docker tests
    - language: none
      os: linux
      sudo: required
      services:
        - docker
      script:
        - docker build . -t semux:latest
        - docker run -d -p 5161:5161 semux:latest --password=""
        - timeout 10 .travis/docker_test_build.sh
        - docker kill $(docker ps -q)
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/Library/Caches/Homebrew
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source .travis/linux_start_xvfb.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then .travis/macos_install_jdk8.sh; fi
