language: java
matrix:
  include:
    # License, formatter, and FindBugs check
    - env: NAME="License, formatter, and FindBugs check"
      os: linux
      sudo: false
      jdk: oraclejdk8
      script:
        - mvn license:check
        - mvn formatter:validate
        - mvn findbugs:check

    # Coverage report
    - env: NAME="Coverage report"
      os: linux
      sudo: false
      jdk: oraclejdk8
      script:
        - mvn cobertura:cobertura
      after_success:
        - mvn coveralls:report

    # Linux tests (java 8)
    - env: NAME="Linux tests (java 8)"
      os: linux
      sudo: false
      jdk: oraclejdk8
      script:
        - mvn test

    # Linux tests (java 9)
    - env: NAME="Linux tests (java 9)"
      os: linux
      sudo: false
      jdk: oraclejdk9
      script:
        - mvn test

    # macOS tests
    - env: NAME="macOS tests"
      os: osx
      osx_image: xcode9.2
      script:
        - mvn test

allow_failures:
    # Docker tests
    - env: NAME="Docker tests"
      language: none
      os: linux
      sudo: required
      services:
        - docker
      script:
        - docker build . -t semux:latest
        - docker run -d -p 5161:5161 semux:latest --password=""
        - timeout 10 .travis/docker_test_build.sh
        - docker kill $(docker ps -q)
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/Library/Caches/Homebrew
before_install:
  - rm ~/.m2/settings.xml || true # remove the default settings.xml in order to use custom repos
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source .travis/linux_start_xvfb.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then .travis/macos_install_jdk8.sh; fi
