version: "{build} ({branch})"

shallow_clone: false
clone_depth: 1
clone_folder: C:\projects\semux

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      Launch4j: debug
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
      Launch4j: debug

install:
  - echo %PATH%
  - echo %M2_HOME%
  - mvn -X -v

# disable MSBuild
build: off

build_script:
  - cd C:\projects\semux
  - mvn clean install -DskipTests

test_script:
  - mvn verify

cache:
  - C:\Users\appveyor\.m2\
